name: NexusBackend-Demo-MinecraftPlugin
main: com.tesseractsoftwares.nexusbackend.demo.minecraftplugin.NexusBackendPlugin
version: "1.0"
author: Tesseract Softwares
api-version: "1.20"

commands:
  login:
    description: Start session on the server
    aliases:
      - lg
    usage: /login <email> <password>

