name: NexusBackend-Demo-MinecraftPlugin
main: com.tesseractsoftwares.nexusbackend.demo.minecraftplugin.NexusBackendPlugin
version: "1.0.3"
author: Tesseract Softwares
api-version: "1.20"

commands:
  login:
    description: Start session on the server
    aliases:
      - lg
    usage: /login <email> <password>

  getplayerinfo:
    description: Get the info of player
    aliases:
      - gpi
    usage: /getplayerinfo

  register:
    description: Register command, show you the URL of the main page to register
    aliases:
      - rg
    usage: /register